### ISSUE TITLE
Lutris script Rayman issue

### ISSUE THREAD

**Issue by legluondunet** [Snaggly/LutrisScripts#1]
Hello Snaggly,
could you remove links from your Rayman Forever Lutris script to my Github files please?
This don't bother me if you use my code, but I prefer you use directly files from your Github account, thanks.

**Comment by Snaggly** [comment]
Hey, 
thank you for your notice! I just submitted another install script with the link to your GitHub removed. I apologize for having caused an inconvenience to you !
Regards

**Comment by legluondunet** [comment]
and here? https://lutris.net/games/rayman-forever/

**Comment by Snaggly** [comment]
Yes, thats where I sent the updated install script to moderation. All I can do now is wait.

**Comment by legluondunet** [comment]
Strange, I'm Lutris administrator and I don't see your modifications. Could you copy/paste your full script code here please, I will update it myself.

**Comment by Snaggly** [comment]
Something must have gotten wrong yesterday..
Here is the updated script:

```
custom-name: Rayman Forever - GOG - DOSBOX
dosbox:
  runner_executable: $GAMEDIR/DOSBOX/dosbox
files:
- game: N/A:Please select the GOG installer
- tplsDOS: https://github.com/Snaggly/LutrisScripts/raw/master/Rayman/RaymanTPLS.tar.xz
- ost: https://github.com/Snaggly/LutrisScripts/raw/master/Rayman/CompleteOST.tar.xz
- config: https://github.com/Snaggly/LutrisScripts/raw/master/Rayman/RaymanForever.conf
game:
  config_file: $GAMEDIR/DOSBOX/RaymanForever.conf
  main_file: $GAMEDIR/Rayman/RAYMAN.EXE
  working_dir: $GAMEDIR/DOSBOX
installer:
- extract:
    dst: $GAMEDIR
    src: game
- chmodx: script
- execute:
    file: script
- extract:
    dst: $GAMEDIR/DOSBOX
    src: tplsDOS
- merge:
    dst: $GAMEDIR/DOSBOX
    src: config
- extract:
    dst: $GAMEDIR
    src: ost
require-binaries: innoextract
```
